// Charts Constants
export const SET_STATE_CHART_OPTIONS_CLUSTERS_ERLANG =
  'SET_STATE_CHART_OPTIONS_CLUSTERS_ERLANG'
export const SET_STATE_CHART_OPTIONS_CLUSTERS_PAYLOAD =
  'SET_STATE_CHART_OPTIONS_CLUSTERS_PAYLOAD'
export const SET_STATE_CHART_OPTIONS_CLUSTERS_CCR =
  'SET_STATE_CHART_OPTIONS_CLUSTERS_CCR'
export const SET_STATE_CHART_OPTIONS_CLUSTERS_PCR =
  'SET_STATE_CHART_OPTIONS_CLUSTERS_PCR'
export const SET_STATE_CHART_OPTIONS_CLUSTERS_USERS =
  'SET_STATE_CHART_OPTIONS_CLUSTERS_USERS'

export const SET_CONFIG_CLEAN_SERIES_CLUSTERS_ERLANG =
  'SET_CONFIG_CLEAN_SERIES_CLUSTERS_ERLANG'
export const SET_CONFIG_CLEAN_SERIES_CLUSTERS_PAYLOAD =
  'SET_CONFIG_CLEAN_SERIES_CLUSTERS_PAYLOAD'
export const SET_CONFIG_CLEAN_SERIES_CLUSTERS_CCR =
  'SET_CONFIG_CLEAN_SERIES_CLUSTERS_CCR'
export const SET_CONFIG_CLEAN_SERIES_CLUSTERS_PCR =
  'SET_CONFIG_CLEAN_SERIES_CLUSTERS_PCR'
export const SET_CONFIG_CLEAN_SERIES_CLUSTERS_USERS =
  'SET_CONFIG_CLEAN_SERIES_CLUSTERS_USERS'

export const SET_PRELOADER_STATE_CLUSTERS_ERLANG =
  'SET_PRELOADER_STATE_CLUSTERS_ERLANG'
export const SET_PRELOADER_STATE_CLUSTERS_PAYLOAD =
  'SET_PRELOADER_STATE_CLUSTERS_PAYLOAD'
export const SET_PRELOADER_STATE_CLUSTERS_CCR =
  'SET_PRELOADER_STATE_CLUSTERS_CCR'
export const SET_PRELOADER_STATE_CLUSTERS_PCR =
  'SET_PRELOADER_STATE_CLUSTERS_PCR'
export const SET_PRELOADER_STATE_CLUSTERS_USERS =
  'SET_PRELOADER_STATE_CLUSTERS_USERS'

//Breadcrumb constants
export const MENU_SELECTOR_LAPSE_CLUSTERS = 'MENU_SELECTOR_LAPSE_CLUSTERS'

export const SHOW_REGION_CLUSTERS = 'SHOW_REGION_CLUSTERS'
export const SEARCH_REGION_CLUSTERS = 'SEARCH_REGION_CLUSTERS'
export const REGION_SUGGESTIONS_CLUSTERS = 'REGION_SUGGESTIONS_CLUSTERS'
export const SELECTED_REGION_CLUSTERS = 'SELECTED_REGION_CLUSTERS'

export const SHOW_CLUSTER = 'SHOW_CLUSTER'
export const SEARCH_CLUSTERS = 'SEARCH_CLUSTERS'
export const CLUSTERS_SUGGESTIONS = 'CLUSTERS_SUGGESTIONS'
export const SELECTED_CLUSTER = 'SELECTED_CLUSTER'

export const MODAL_CALENDAR_CLUSTERS = 'MODAL_CALENDAR_CLUSTERS'
export const SET_CALENDAR_DATE_START_CLUSTERS =
  'SET_CALENDAR_DATE_START_CLUSTERS'
export const SET_CALENDAR_DATE_END_CLUSTERS = 'SET_CALENDAR_DATE_END_CLUSTERS'
export const SET_SELECTED_TIME_LAPSE_CLUSTERS =
  'SET_SELECTED_TIME_LAPSE_CLUSTERS'

export const REGION_INPUT_CHANGE_CLUSTERS = 'REGION_INPUT_CHANGE_CLUSTERS'
export const CLUSTERS_INPUT_CHANGE = 'CLUSTERS_INPUT_CHANGE'

//API RESQUESTS
export const REGION_REQUESTING_CLUSTERS = 'REGION_REQUESTING_CLUSTERS'
export const REGION_SUCCESS_CLUSTERS = 'REGION_SUCCESS_CLUSTERS'

export const CLUSTERS_REQUESTING = 'CLUSTERS_REQUESTING'
export const CLUSTERS_SUCCESS = 'CLUSTERS_SUCCESS'

export const STATISTICS_REQUESTING_CLUSTERS_ERLANG =
  'STATISTICS_REQUESTING_CLUSTERS_ERLANG'
export const STATISTICS_SUCCESS_CLUSTERS_ERLANG =
  'STATISTICS_SUCCESS_CLUSTERS_ERLANG'

export const STATISTICS_REQUESTING_CLUSTERS_PAYLOAD =
  'STATISTICS_REQUESTING_CLUSTERS_PAYLOAD'
export const STATISTICS_SUCCESS_CLUSTERS_PAYLOAD =
  'STATISTICS_SUCCESS_CLUSTERS_PAYLOAD'

export const STATISTICS_REQUESTING_CLUSTERS_CCR =
  'STATISTICS_REQUESTING_CLUSTERS_CCR'
export const STATISTICS_SUCCESS_CLUSTERS_CCR = 'STATISTICS_SUCCESS_CLUSTERS_CCR'

export const STATISTICS_REQUESTING_CLUSTERS_PCR =
  'STATISTICS_REQUESTING_CLUSTERS_PCR'
export const STATISTICS_SUCCESS_CLUSTERS_PCR = 'STATISTICS_SUCCESS_CLUSTERS_PCR'

export const STATISTICS_REQUESTING_CLUSTERS_USERS =
  'STATISTICS_REQUESTING_CLUSTERS_USERS'
export const STATISTICS_SUCCESS_CLUSTERS_USERS =
  'STATISTICS_SUCCESS_CLUSTERS_USERS'

//Charts Options
export const SET_CHART_OPTIONS_CLUSTERS_ERLANG =
  'SET_CHART_OPTIONS_CLUSTERS_ERLANG'
export const SET_CHART_OPTIONS_CLUSTERS_PAYLOAD =
  'SET_CHART_OPTIONS_CLUSTERS_PAYLOAD'
export const SET_CHART_OPTIONS_CLUSTERS_CCR = 'SET_CHART_OPTIONS_CLUSTERS_CCR'
export const SET_CHART_OPTIONS_CLUSTERS_PCR = 'SET_CHART_OPTIONS_CLUSTERS_PCR'
export const SET_CHART_OPTIONS_CLUSTERS_USERS =
  'SET_CHART_OPTIONS_CLUSTERS_USERS'

export const SELECTED_GROUP_CLUSTERS = 'SELECTED_GROUP_CLUSTERS'

export const SET_STATE_GROUP_MENU_CLUSTERS = 'SET_STATE_GROUP_MENU_CLUSTERS'

export const CHANGE_CONSULT_STATE_CLUSTERS = 'CHANGE_CONSULT_STATE_CLUSTERS'

export const SET_CHART_OPTIONS_CLUSTERS_CONSULT =
  'SET_CHART_OPTIONS_CLUSTERS_CONSULT'

export const SET_STATE_CHART_OPTIONS_CLUSTERS_CONSULT =
  'SET_STATE_CHART_OPTIONS_CLUSTERS_CONSULT'

export const SET_PRELOADER_STATE_CLUSTERS_CONSULT =
  'SET_PRELOADER_STATE_CLUSTERS_CONSULT'

export const STATISTICS_SUCCESS_CLUSTERS_CONSULT =
  'STATISTICS_SUCCESS_CLUSTERS_CONSULT'

export const SELECTED_SERVICE_CLUSTERS_CONSULT =
  'SELECTED_SERVICE_CLUSTERS_CONSULT'

export const STATISTICS_REQUESTING_CLUSTERS_CONSULT =
  'STATISTICS_REQUESTING_CLUSTERS_CONSULT'

export const SET_CONFIG_CLEAN_SERIES_CLUSTERS_CONSULT =
  'SET_CONFIG_CLEAN_SERIES_CLUSTERS_CONSULT'
