export const SET_STATE_CHART_OPTIONS_CCRPCR = 'SET_STATE_CHART_OPTIONS_CCRPCR'
export const SET_CONFIG_CLEAN_SERIES_CCRPCR = 'SET_CONFIG_CLEAN_SERIES_CCRPCR'
export const SET_PRELOADER_STATE_CCRPCR = 'SET_PRELOADER_STATE_CCRPCR'

//Breadcrumb constants

export const MENU_SELECTOR_LAPSE_CCRPCR = 'MENU_SELECTOR_LAPSE_CCRPCR'

export const MENU_SELECTOR_SERVICE_CCRPCR = 'MENU_SELECTOR_SERVICE_CCRPCR'
export const SELECTED_SERVICE_CCRPCR = 'SELECTED_SERVICE_CCRPCR'

export const SHOW_REGION_CCRPCR = 'SHOW_REGION_CCRPCR'
export const SEARCH_REGION_CCRPCR = 'SEARCH_REGION_CCRPCR'
export const REGION_SUGGESTIONS_CCRPCR = 'REGION_SUGGESTIONS_CCRPCR'
export const SELECTED_REGION_CCRPCR = 'SELECTED_REGION_CCRPCR'

export const SHOW_STATION_CCRPCR = 'SHOW_STATION_CCRPCR'
export const SEARCH_STATION_CCRPCR = 'SEARCH_STATIONS_CCRPCR'
export const STATION_SUGGESTIONS_CCRPCR = 'STATION_SUGGESTIONS_CCRPCR'
export const SELECTED_STATION_CCRPCR = 'SELECTED_STATION_CCRPCR'

export const SHOW_SECTOR_CCRPCR = 'SHOW_SECTOR_CCRPCR'
export const SEARCH_SECTOR_CCRPCR = 'SEARCH_SECTOR_CCRPCR'
export const SECTOR_SUGGESTIONS_CCRPCR = 'SECTOR_SUGGESTIONS_CCRPCR'
export const SELECTED_SECTOR_CCRPCR = 'SELECTED_SECTOR_CCRPCR'

export const MODAL_CALENDAR_CCRPCR = 'MODAL_CALENDAR_CCRPCR'
export const SET_CALENDAR_DATE_START_CCRPCR = 'SET_CALENDAR_DATE_START_CCRPCR'
export const SET_CALENDAR_DATE_END_CCRPCR = 'SET_CALENDAR_DATE_END_CCRPCR'
export const SET_SELECTED_TIME_LAPSE_CCRPCR = 'SET_SELECTED_TIME_LAPSE_CCRPCR'

export const REGION_INPUT_CHANGE_CCRPCR = 'REGION_INPUT_CHANGE_CCRPCR'
export const STATION_INPUT_CHANGE_CCRPCR = 'STATION_INPUT_CHANGE_CCRPCR'
export const SECTOR_INPUT_CHANGE_CCRPCR = 'SECTOR_INPUT_CHANGE_CCRPCR'

//API RESQUESTS
export const SERVICE_REQUESTING_CCRPCR = 'SERVICE_REQUESTING_CCRPCR'
export const SERVICE_SUCCESS_CCRPCR = 'SERVICE_SUCCESS_CCRPCR'

export const REGION_REQUESTING_CCRPCR = 'REGION_REQUESTING_CCRPCR'
export const REGION_SUCCESS_CCRPCR = 'REGION_SUCCESS_CCRPCR'

export const STATION_REQUESTING_CCRPCR = 'STATION_REQUESTING_CCRPCR'
export const STATION_SUCCESS_CCRPCR = 'STATION_SUCCESS_CCRPCR'

export const SECTOR_REQUESTING_CCRPCR = 'SECTOR_REQUESTING_CCRPCR'
export const SECTOR_SUCCESS_CCRPCR = 'SECTOR_SUCCESS_CCRPCR'

export const STATISTICS_REQUESTING_CCRPCR = 'STATISTICS_REQUESTING_CCRPCR'
export const STATISTICS_SUCCESS_CCRPCR = 'STATISTICS_SUCCESS_CCRPCR'

export const SET_CHART_OPTIONS_CCRPCR = 'SET_CHART_OPTIONS_CCRPCR'
export const SELECTED_GROUP_CCRPCR = 'SELECTED_GROUP_CCRPCR'
export const SET_STATE_GROUP_MENU_CCRPCR = 'SET_STATE_GROUP_MENU_CCRPCR'
