export const SET_MODAL_OPEN_STATE = 'SET_MODAL_OPEN_STATE'
export const SET_PRELOADER_STATE_MORE_ALERT_DETAILS =
  'SET_PRELOADER_STATE_MORE_ALERT_DETAILS'
export const STATISTICS_SUCCESS_MORE_ALERT_DETAILS =
  'STATISTICS_SUCCESS_MORE_ALERT_DETAILS'
export const SET_ALERT_DATA = 'SET_ALERT_DATA'
export const STATISTICS_REQUESTING_MORE_ALERT_DETAILS =
  'STATISTICS_REQUESTING_MORE_ALERT_DETAILS'
export const SET_CONFIG_CLEAN_SERIES_MORE_ALERT_DETAILS =
  'SET_CONFIG_CLEAN_SERIES_MORE_ALERT_DETAILS'
