export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const UPDATE_USER_REQUEST = 'UPDATE_USERS_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USERS_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USERS_ERROR'

export const DELETE_USER_REQUEST = 'DELETE_USERS_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USERS_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USERS_ERROR'

export const SET_FETCH_STATE_USERS = 'SET_FETCH_STATE_USERS'
