export const REGION_REQUESTING = 'REGION_REQUESTING'
export const REGION_SUCCESS = 'REGION_SUCCESS'
export const REGION_ERROR = 'REGION_ERROR'

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_EXISTING = 'LOGIN_EXISTING'
export const LOGOUT = 'LOGOUT'

export const CHANGE_TO_SIGNUP = 'CHANGE_TO_SIGNUP'
export const CHANGE_TO_LOGIN = 'CHANGE_TO_LOGIN'

export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const RESET_FLATS = 'RESET_FLATS'
