export const SET_STATE_CHART_OPTIONS_PAYLOAD = 'SET_STATE_CHART_OPTIONS_PAYLOAD'
export const SET_CONFIG_CLEAN_SERIES_PAYLOAD = 'SET_CONFIG_CLEAN_SERIES_PAYLOAD'
export const SET_PRELOADER_STATE_PAYLOAD = 'SET_PRELOADER_STATE_PAYLOAD'

//Breadcrumb constants

export const MENU_SELECTOR_LAPSE_PAYLOAD = 'MENU_SELECTOR_LAPSE_PAYLOAD'

export const MENU_SELECTOR_SERVICE_PAYLOAD = 'MENU_SELECTOR_SERVICE_PAYLOAD'
export const SELECTED_SERVICE_PAYLOAD = 'SELECTED_SERVICE_PAYLOAD'

export const SHOW_REGION_PAYLOAD = 'SHOW_REGION_PAYLOAD'
export const SEARCH_REGION_PAYLOAD = 'SEARCH_REGION_PAYLOAD'
export const REGION_SUGGESTIONS_PAYLOAD = 'REGION_SUGGESTIONS_PAYLOAD'
export const SELECTED_REGION_PAYLOAD = 'SELECTED_REGION_PAYLOAD'

export const SHOW_STATION_PAYLOAD = 'SHOW_STATION_PAYLOAD'
export const SEARCH_STATION_PAYLOAD = 'SEARCH_STATIONS_PAYLOAD'
export const STATION_SUGGESTIONS_PAYLOAD = 'STATION_SUGGESTIONS_PAYLOAD'
export const SELECTED_STATION_PAYLOAD = 'SELECTED_STATION_PAYLOAD'

export const SHOW_SECTOR_PAYLOAD = 'SHOW_SECTOR_PAYLOAD'
export const SEARCH_SECTOR_PAYLOAD = 'SEARCH_SECTOR_PAYLOAD'
export const SECTOR_SUGGESTIONS_PAYLOAD = 'SECTOR_SUGGESTIONS_PAYLOAD'
export const SELECTED_SECTOR_PAYLOAD = 'SELECTED_SECTOR_PAYLOAD'

export const MODAL_CALENDAR_PAYLOAD = 'MODAL_CALENDAR_PAYLOAD'
export const SET_CALENDAR_DATE_START_PAYLOAD = 'SET_CALENDAR_DATE_START_PAYLOAD'
export const SET_CALENDAR_DATE_END_PAYLOAD = 'SET_CALENDAR_DATE_END_PAYLOAD'
export const SET_SELECTED_TIME_LAPSE_PAYLOAD = 'SET_SELECTED_TIME_LAPSE_PAYLOAD'

export const REGION_INPUT_CHANGE_PAYLOAD = 'REGION_INPUT_CHANGE_PAYLOAD'
export const STATION_INPUT_CHANGE_PAYLOAD = 'STATION_INPUT_CHANGE_PAYLOAD'
export const SECTOR_INPUT_CHANGE_PAYLOAD = 'SECTOR_INPUT_CHANGE_PAYLOAD'

//API RESQUESTS
export const SERVICE_REQUESTING_PAYLOAD = 'SERVICE_REQUESTING_PAYLOAD'
export const SERVICE_SUCCESS_PAYLOAD = 'SERVICE_SUCCESS_PAYLOAD'

export const REGION_REQUESTING_PAYLOAD = 'REGION_REQUESTING_PAYLOAD'
export const REGION_SUCCESS_PAYLOAD = 'REGION_SUCCESS_PAYLOAD'

export const STATION_REQUESTING_PAYLOAD = 'STATION_REQUESTING_PAYLOAD'
export const STATION_SUCCESS_PAYLOAD = 'STATION_SUCCESS_PAYLOAD'

export const SECTOR_REQUESTING_PAYLOAD = 'SECTOR_REQUESTING_PAYLOAD'
export const SECTOR_SUCCESS_PAYLOAD = 'SECTOR_SUCCESS_PAYLOAD'

export const STATISTICS_REQUESTING_PAYLOAD = 'STATISTICS_REQUESTING_PAYLOAD'
export const STATISTICS_SUCCESS_PAYLOAD = 'STATISTICS_SUCCESS_PAYLOAD'

export const SET_CHART_OPTIONS_PAYLOAD = 'SET_CHART_OPTIONS_PAYLOAD'
export const SELECTED_GROUP_PAYLOAD = 'SELECTED_GROUP_PAYLOAD'
export const SET_STATE_GROUP_MENU_PAYLOAD = 'SET_STATE_GROUP_MENU_PAYLOAD'
