// Charts Constants
export const SET_STATE_CHART_OPTIONS_MARKETS_ERLANG =
  'SET_STATE_CHART_OPTIONS_MARKETS_ERLANG'
export const SET_STATE_CHART_OPTIONS_MARKETS_PAYLOAD =
  'SET_STATE_CHART_OPTIONS_MARKETS_PAYLOAD'
export const SET_STATE_CHART_OPTIONS_MARKETS_CCR =
  'SET_STATE_CHART_OPTIONS_MARKETS_CCR'
export const SET_STATE_CHART_OPTIONS_MARKETS_PCR =
  'SET_STATE_CHART_OPTIONS_MARKETS_PCR'
export const SET_STATE_CHART_OPTIONS_MARKETS_USERS =
  'SET_STATE_CHART_OPTIONS_MARKETS_USERS'

export const SET_CONFIG_CLEAN_SERIES_MARKETS_ERLANG =
  'SET_CONFIG_CLEAN_SERIES_MARKETS_ERLANG'
export const SET_CONFIG_CLEAN_SERIES_MARKETS_PAYLOAD =
  'SET_CONFIG_CLEAN_SERIES_MARKETS_PAYLOAD'
export const SET_CONFIG_CLEAN_SERIES_MARKETS_CCR =
  'SET_CONFIG_CLEAN_SERIES_MARKETS_CCR'
export const SET_CONFIG_CLEAN_SERIES_MARKETS_PCR =
  'SET_CONFIG_CLEAN_SERIES_MARKETS_PCR'
export const SET_CONFIG_CLEAN_SERIES_MARKETS_USERS =
  'SET_CONFIG_CLEAN_SERIES_MARKETS_USERS'

export const SET_PRELOADER_STATE_MARKETS_ERLANG =
  'SET_PRELOADER_STATE_MARKETS_ERLANG'
export const SET_PRELOADER_STATE_MARKETS_PAYLOAD =
  'SET_PRELOADER_STATE_MARKETS_PAYLOAD'
export const SET_PRELOADER_STATE_MARKETS_CCR = 'SET_PRELOADER_STATE_MARKETS_CCR'
export const SET_PRELOADER_STATE_MARKETS_PCR = 'SET_PRELOADER_STATE_MARKETS_PCR'
export const SET_PRELOADER_STATE_MARKETS_USERS =
  'SET_PRELOADER_STATE_MARKETS_USERS'

//Breadcrumb constants
export const MENU_SELECTOR_LAPSE_MARKETS = 'MENU_SELECTOR_LAPSE_MARKETS'

export const SHOW_REGION_MARKETS = 'SHOW_REGION_MARKETS'
export const SEARCH_REGION_MARKETS = 'SEARCH_REGION_MARKETS'
export const REGION_SUGGESTIONS_MARKETS = 'REGION_SUGGESTIONS_MARKETS'
export const SELECTED_REGION_MARKETS = 'SELECTED_REGION_MARKETS'

export const SHOW_MARKET = 'SHOW_MARKET'
export const SEARCH_MARKETS = 'SEARCH_MARKETS'
export const MARKETS_SUGGESTIONS = 'MARKETS_SUGGESTIONS'
export const SELECTED_MARKET = 'SELECTED_MARKET'

export const MODAL_CALENDAR_MARKETS = 'MODAL_CALENDAR_MARKETS'
export const SET_CALENDAR_DATE_START_MARKETS = 'SET_CALENDAR_DATE_START_MARKETS'
export const SET_CALENDAR_DATE_END_MARKETS = 'SET_CALENDAR_DATE_END_MARKETS'
export const SET_SELECTED_TIME_LAPSE_MARKETS = 'SET_SELECTED_TIME_LAPSE_MARKETS'

export const REGION_INPUT_CHANGE_MARKETS = 'REGION_INPUT_CHANGE_MARKETS'
export const MARKETS_INPUT_CHANGE = 'MARKETS_INPUT_CHANGE'

//API RESQUESTS
export const REGION_REQUESTING_MARKETS = 'REGION_REQUESTING_MARKETS'
export const REGION_SUCCESS_MARKETS = 'REGION_SUCCESS_MARKETS'

export const MARKETS_REQUESTING = 'MARKETS_REQUESTING'
export const MARKETS_SUCCESS = 'MARKETS_SUCCESS'

export const STATISTICS_REQUESTING_MARKETS_ERLANG =
  'STATISTICS_REQUESTING_MARKETS_ERLANG'
export const STATISTICS_SUCCESS_MARKETS_ERLANG =
  'STATISTICS_SUCCESS_MARKETS_ERLANG'

export const STATISTICS_REQUESTING_MARKETS_PAYLOAD =
  'STATISTICS_REQUESTING_MARKETS_PAYLOAD'
export const STATISTICS_SUCCESS_MARKETS_PAYLOAD =
  'STATISTICS_SUCCESS_MARKETS_PAYLOAD'

export const STATISTICS_REQUESTING_MARKETS_CCR =
  'STATISTICS_REQUESTING_MARKETS_CCR'
export const STATISTICS_SUCCESS_MARKETS_CCR = 'STATISTICS_SUCCESS_MARKETS_CCR'

export const STATISTICS_REQUESTING_MARKETS_PCR =
  'STATISTICS_REQUESTING_MARKETS_PCR'
export const STATISTICS_SUCCESS_MARKETS_PCR = 'STATISTICS_SUCCESS_MARKETS_PCR'

export const STATISTICS_REQUESTING_MARKETS_USERS =
  'STATISTICS_REQUESTING_MARKETS_USERS'
export const STATISTICS_SUCCESS_MARKETS_USERS =
  'STATISTICS_SUCCESS_MARKETS_USERS'

//Charts Options
export const SET_CHART_OPTIONS_MARKETS_ERLANG =
  'SET_CHART_OPTIONS_MARKETS_ERLANG'
export const SET_CHART_OPTIONS_MARKETS_PAYLOAD =
  'SET_CHART_OPTIONS_MARKETS_PAYLOAD'
export const SET_CHART_OPTIONS_MARKETS_CCR = 'SET_CHART_OPTIONS_MARKETS_CCR'
export const SET_CHART_OPTIONS_MARKETS_PCR = 'SET_CHART_OPTIONS_MARKETS_PCR'
export const SET_CHART_OPTIONS_MARKETS_USERS = 'SET_CHART_OPTIONS_MARKETS_USERS'

export const SELECTED_GROUP_MARKETS = 'SELECTED_GROUP_MARKETS'

export const SET_STATE_GROUP_MENU_MARKETS = 'SET_STATE_GROUP_MENU_MARKETS'

export const CHANGE_CONSULT_STATE_MARKETS = 'CHANGE_CONSULT_STATE_MARKETS'

export const SET_CHART_OPTIONS_MARKETS_CONSULT =
  'SET_CHART_OPTIONS_MARKETS_CONSULT'

export const SET_STATE_CHART_OPTIONS_MARKETS_CONSULT =
  'SET_STATE_CHART_OPTIONS_MARKETS_CONSULT'

export const SET_PRELOADER_STATE_MARKETS_CONSULT =
  'SET_PRELOADER_STATE_MARKETS_CONSULT'

export const STATISTICS_SUCCESS_MARKETS_CONSULT =
  'STATISTICS_SUCCESS_MARKETS_CONSULT'

export const SELECTED_SERVICE_MARKETS_CONSULT =
  'SELECTED_SERVICE_MARKETS_CONSULT'

export const STATISTICS_REQUESTING_MARKETS_CONSULT =
  'STATISTICS_REQUESTING_MARKETS_CONSULT'

export const SET_CONFIG_CLEAN_SERIES_MARKETS_CONSULT =
  'SET_CONFIG_CLEAN_SERIES_MARKETS_CONSULT'
