export const SET_STATE_CHART_OPTIONS_DROPCALLCSFHOF =
  'SET_STATE_CHART_OPTIONS_DROPCALLCSFHOF'
export const SET_CONFIG_CLEAN_SERIES_DROPCALLCSFHOF =
  'SET_CONFIG_CLEAN_SERIES_DROPCALLCSFHOF'
export const SET_PRELOADER_STATE_DROPCALLCSFHOF =
  'SET_PRELOADER_STATE_DROPCALLCSFHOF'

//Breadcrumb constants

export const MENU_SELECTOR_LAPSE_DROPCALLCSFHOF =
  'MENU_SELECTOR_LAPSE_DROPCALLCSFHOF'

export const MENU_SELECTOR_SERVICE_DROPCALLCSFHOF =
  'MENU_SELECTOR_SERVICE_DROPCALLCSFHOF'
export const SELECTED_SERVICE_DROPCALLCSFHOF = 'SELECTED_SERVICE_DROPCALLCSFHOF'

export const SHOW_REGION_DROPCALLCSFHOF = 'SHOW_REGION_DROPCALLCSFHOF'
export const SEARCH_REGION_DROPCALLCSFHOF = 'SEARCH_REGION_DROPCALLCSFHOF'
export const REGION_SUGGESTIONS_DROPCALLCSFHOF =
  'REGION_SUGGESTIONS_DROPCALLCSFHOF'
export const SELECTED_REGION_DROPCALLCSFHOF = 'SELECTED_REGION_DROPCALLCSFHOF'

export const SHOW_CLUSTER_DROPCALLCSFHOF = 'SHOW_CLUSTER_DROPCALLCSFHOF'
export const SEARCH_CLUSTER_DROPCALLCSFHOF = 'SEARCH_CLUSTERS_DROPCALLCSFHOF'
export const CLUSTER_SUGGESTIONS_DROPCALLCSFHOF =
  'CLUSTER_SUGGESTIONS_DROPCALLCSFHOF'
export const SELECTED_CLUSTER_DROPCALLCSFHOF = 'SELECTED_CLUSTER_DROPCALLCSFHOF'

export const MODAL_CALENDAR_DROPCALLCSFHOF = 'MODAL_CALENDAR_DROPCALLCSFHOF'
export const SET_CALENDAR_DATE_START_DROPCALLCSFHOF =
  'SET_CALENDAR_DATE_START_DROPCALLCSFHOF'
export const SET_CALENDAR_DATE_END_DROPCALLCSFHOF =
  'SET_CALENDAR_DATE_END_DROPCALLCSFHOF'
export const SET_SELECTED_TIME_LAPSE_DROPCALLCSFHOF =
  'SET_SELECTED_TIME_LAPSE_DROPCALLCSFHOF'

export const REGION_INPUT_CHANGE_DROPCALLCSFHOF =
  'REGION_INPUT_CHANGE_DROPCALLCSFHOF'
export const CLUSTER_INPUT_CHANGE_DROPCALLCSFHOF =
  'CLUSTER_INPUT_CHANGE_DROPCALLCSFHOF'

//API RESQUESTS
export const SERVICE_REQUESTING_DROPCALLCSFHOF =
  'SERVICE_REQUESTING_DROPCALLCSFHOF'
export const SERVICE_SUCCESS_DROPCALLCSFHOF = 'SERVICE_SUCCESS_DROPCALLCSFHOF'

export const REGION_REQUESTING_DROPCALLCSFHOF =
  'REGION_REQUESTING_DROPCALLCSFHOF'
export const REGION_SUCCESS_DROPCALLCSFHOF = 'REGION_SUCCESS_DROPCALLCSFHOF'

export const CLUSTER_REQUESTING_DROPCALLCSFHOF =
  'CLUSTER_REQUESTING_DROPCALLCSFHOF'
export const CLUSTER_SUCCESS_DROPCALLCSFHOF = 'CLUSTER_SUCCESS_DROPCALLCSFHOF'

export const SECTOR_REQUESTING_DROPCALLCSFHOF =
  'SECTOR_REQUESTING_DROPCALLCSFHOF'
export const SECTOR_SUCCESS_DROPCALLCSFHOF = 'SECTOR_SUCCESS_DROPCALLCSFHOF'

export const STATISTICS_REQUESTING_DROPCALLCSFHOF =
  'STATISTICS_REQUESTING_DROPCALLCSFHOF'
export const STATISTICS_SUCCESS_DROPCALLCSFHOF =
  'STATISTICS_SUCCESS_DROPCALLCSFHOF'

export const SET_CHART_OPTIONS_DROPCALLCSFHOF =
  'SET_CHART_OPTIONS_DROPCALLCSFHOF'
export const SELECTED_GROUP_DROPCALLCSFHOF = 'SELECTED_GROUP_DROPCALLCSFHOF'
export const SET_STATE_GROUP_MENU_DROPCALLCSFHOF =
  'SET_STATE_GROUP_MENU_DROPCALLCSFHOF'
