export const SET_CHANGE_TO_OTHER_VIEW_MTD_KPI =
  'SET_CHANGE_TO_OTHER_VIEW_MTD_KPI'
export const SET_CHANGE_TO_OTHER_VIEW_TOP_ERLANG =
  'SET_CHANGE_TO_OTHER_VIEW_TOP_ERLANG'
export const SET_CHANGE_TO_OTHER_VIEW_TOP_PAYLOAD =
  'SET_CHANGE_TO_OTHER_VIEW_TOP_PAYLOAD'
export const SET_CHANGE_TO_OTHER_VIEW_NEW_STATIONS =
  'SET_CHANGE_TO_OTHER_VIEW_NEW_STATIONS'
export const SET_HOVER_LEAVE_REGION_LOCK = 'SET_HOVER_LEAVE_REGION_LOCK'
export const SET_DROP_MENU_REGION_SELECTOR = 'SET_DROP_MENU_REGION_SELECTOR'
export const SET_STATE_HI_MESSAGE = 'SET_STATE_HI_MESSAGE'

export const SET_COMPLETE_FETCH_DATA_PAYLOAD_MTD =
  'SET_COMPLETE_FETCH_DATA_PAYLOAD_MTD'

export const SET_COMPLETE_FETCH_DATA_ERLANG_MTD =
  'SET_COMPLETE_FETCH_DATA_ERLANG_MTD'

export const SET_COMPLETE_FETCH_DATA_PAYLOAD_BY_MONTH =
  'SET_COMPLETE_FETCH_DATA_PAYLOAD_BY_MONTH'

export const SET_COMPLETE_FETCH_DATA_ERLANG_BY_MONTH =
  'SET_COMPLETE_FETCH_DATA_ERLANG_BY_MONTH'

export const ERLANG_UNTIL_30_DAYS_REQUESTING = 'ERLANG_UNTIL_30_DAYS_REQUESTING'
export const ERLANG_UNTIL_30_DAYS_SUCCESS = 'ERLANG_UNTIL_30_DAYS_SUCCESS'

export const PAYLOAD_UNTIL_30_DAYS_REQUESTING =
  'PAYLOAD_UNTIL_30_DAYS_REQUESTING'
export const PAYLOAD_UNTIL_30_DAYS_SUCCESS = 'PAYLOAD_UNTIL_30_DAYS_SUCCESS'

export const ERLANG_LATEST_12_MONTHS_REQUESTING =
  'ERLANG_LATEST_12_MONTHS_REQUESTING'
export const ERLANG_LATEST_12_MONTHS_SUCCESS = 'ERLANG_LATEST_12_MONTHS_SUCCESS'

export const PAYLOAD_LATEST_12_MONTHS_REQUESTING =
  'PAYLOAD_LATEST_12_MONTHS_REQUESTING'
export const PAYLOAD_LATEST_12_MONTHS_SUCCESS =
  'PAYLOAD_LATEST_12_MONTHS_SUCCESS'

export const SUM_KPI_MONTH_COMP_REQUESTING = 'SUM_KPI_MONTH_COMP_REQUESTING'
export const SUM_KPI_MONTH_COMP_SUCCESS = 'SUM_KPI_MONTH_COMP_SUCCESS'

export const TOP_STATION_ERLANG_REQUESTING = 'TOP_STATION_ERLANG_REQUESTING'
export const TOP_STATION_ERLANG_SUCCESS = 'TOP_STATION_ERLANG_SUCCESS'

export const TOP_STATION_PAYLOAD_REQUESTING = 'TOP_STATION_PAYLOAD_REQUESTING'
export const TOP_STATION_PAYLOAD_SUCCESS = 'TOP_STATION_PAYLOAD_SUCCESS'

export const SET_FIRST_STATION_ERLANG = 'SET_FIRST_STATION_ERLANG'
export const SET_SECOND_STATION_ERLANG = 'SET_SECOND_STATION_ERLANG'
export const SET_THIRD_STATION_ERLANG = 'SET_THIRD_STATION_ERLANG'

export const SET_FIRST_STATION_PAYLOAD = 'SET_FIRST_STATION_PAYLOAD'
export const SET_SECOND_STATION_PAYLOAD = 'SET_SECOND_STATION_PAYLOAD'
export const SET_THIRD_STATION_PAYLOAD = 'SET_THIRD_STATION_PAYLOAD'

export const SET_ERLANG_SUM_MES_ACTUAL = 'SET_ERLANG_SUM_MES_ACTUAL'
export const SET_ERLANG_SUM_MES_ANTERIOR = 'SET_ERLANG_SUM_MES_ANTERIOR'

export const SET_PAYLOAD_SUM_MES_ACTUAL = 'SET_PAYLOAD_SUM_MES_ACTUAL'
export const SET_PAYLOAD_SUM_MES_ANTERIOR = 'SET_PAYLOAD_SUM_MES_ANTERIOR'

export const REGION_DASHBOARD_SUCCESS = 'REGION_DASHBOARD_SUCCESS'
export const SELECTED_DASHBOARD_REGION = 'SELECTED_DASHBOARD_REGION'

export const REGION_DASHBOARD_REQUESTING = 'REGION_DASHBOARD_REQUESTING'

export const GET_ALERTS_DASHBOARD_REQUEST = 'GET_ALERTS_DASHBOARD_REQUEST'
export const GET_ALERTS_DASHBOARD_SUCCESS = 'GET_ALERTS_DASHBOARD_SUCCESS'
