export const SET_STATE_CHART_OPTIONS_THROUGHPUT =
  'SET_STATE_CHART_OPTIONS_THROUGHPUT'
export const SET_CONFIG_CLEAN_SERIES_THROUGHPUT =
  'SET_CONFIG_CLEAN_SERIES_THROUGHPUT'
export const SET_PRELOADER_STATE_THROUGHPUT = 'SET_PRELOADER_STATE_THROUGHPUT'

//Breadcrumb constants

export const MENU_SELECTOR_LAPSE_THROUGHPUT = 'MENU_SELECTOR_LAPSE_THROUGHPUT'

export const MENU_SELECTOR_SERVICE_THROUGHPUT =
  'MENU_SELECTOR_SERVICE_THROUGHPUT'
export const SELECTED_SERVICE_THROUGHPUT = 'SELECTED_SERVICE_THROUGHPUT'

export const SHOW_REGION_THROUGHPUT = 'SHOW_REGION_THROUGHPUT'
export const SEARCH_REGION_THROUGHPUT = 'SEARCH_REGION_THROUGHPUT'
export const REGION_SUGGESTIONS_THROUGHPUT = 'REGION_SUGGESTIONS_THROUGHPUT'
export const SELECTED_REGION_THROUGHPUT = 'SELECTED_REGION_THROUGHPUT'

export const SHOW_STATION_THROUGHPUT = 'SHOW_STATION_THROUGHPUT'
export const SEARCH_STATION_THROUGHPUT = 'SEARCH_STATIONS_THROUGHPUT'
export const STATION_SUGGESTIONS_THROUGHPUT = 'STATION_SUGGESTIONS_THROUGHPUT'
export const SELECTED_STATION_THROUGHPUT = 'SELECTED_STATION_THROUGHPUT'

export const SHOW_SECTOR_THROUGHPUT = 'SHOW_SECTOR_THROUGHPUT'
export const SEARCH_SECTOR_THROUGHPUT = 'SEARCH_SECTOR_THROUGHPUT'
export const SECTOR_SUGGESTIONS_THROUGHPUT = 'SECTOR_SUGGESTIONS_THROUGHPUT'
export const SELECTED_SECTOR_THROUGHPUT = 'SELECTED_SECTOR_THROUGHPUT'

export const MODAL_CALENDAR_THROUGHPUT = 'MODAL_CALENDAR_THROUGHPUT'
export const SET_CALENDAR_DATE_START_THROUGHPUT =
  'SET_CALENDAR_DATE_START_THROUGHPUT'
export const SET_CALENDAR_DATE_END_THROUGHPUT =
  'SET_CALENDAR_DATE_END_THROUGHPUT'
export const SET_SELECTED_TIME_LAPSE_THROUGHPUT =
  'SET_SELECTED_TIME_LAPSE_THROUGHPUT'

export const REGION_INPUT_CHANGE_THROUGHPUT = 'REGION_INPUT_CHANGE_THROUGHPUT'
export const STATION_INPUT_CHANGE_THROUGHPUT = 'STATION_INPUT_CHANGE_THROUGHPUT'
export const SECTOR_INPUT_CHANGE_THROUGHPUT = 'SECTOR_INPUT_CHANGE_THROUGHPUT'

//API RESQUESTS
export const SERVICE_REQUESTING_THROUGHPUT = 'SERVICE_REQUESTING_THROUGHPUT'
export const SERVICE_SUCCESS_THROUGHPUT = 'SERVICE_SUCCESS_THROUGHPUT'

export const REGION_REQUESTING_THROUGHPUT = 'REGION_REQUESTING_THROUGHPUT'
export const REGION_SUCCESS_THROUGHPUT = 'REGION_SUCCESS_THROUGHPUT'

export const STATION_REQUESTING_THROUGHPUT = 'STATION_REQUESTING_THROUGHPUT'
export const STATION_SUCCESS_THROUGHPUT = 'STATION_SUCCESS_THROUGHPUT'

export const SECTOR_REQUESTING_THROUGHPUT = 'SECTOR_REQUESTING_THROUGHPUT'
export const SECTOR_SUCCESS_THROUGHPUT = 'SECTOR_SUCCESS_THROUGHPUT'

export const STATISTICS_REQUESTING_THROUGHPUT =
  'STATISTICS_REQUESTING_THROUGHPUT'
export const STATISTICS_SUCCESS_THROUGHPUT = 'STATISTICS_SUCCESS_THROUGHPUT'

export const SET_CHART_OPTIONS_THROUGHPUT = 'SET_CHART_OPTIONS_THROUGHPUT'
export const SELECTED_GROUP_THROUGHPUT = 'SELECTED_GROUP_THROUGHPUT'
export const SET_STATE_GROUP_MENU_THROUGHPUT = 'SET_STATE_GROUP_MENU_THROUGHPUT'
