export const SET_STATE_CHART_OPTIONS_USERS = 'SET_STATE_CHART_OPTIONS_USERS'
export const SET_CONFIG_CLEAN_SERIES_USERS = 'SET_CONFIG_CLEAN_SERIES_USERS'
export const SET_PRELOADER_STATE_USERS = 'SET_PRELOADER_STATE_USERS'

//Breadcrumb constants

export const MENU_SELECTOR_LAPSE_USERS = 'MENU_SELECTOR_LAPSE_USERS'

export const MENU_SELECTOR_SERVICE_USERS = 'MENU_SELECTOR_SERVICE_USERS'
export const SELECTED_SERVICE_USERS = 'SELECTED_SERVICE_USERS'

export const SHOW_REGION_USERS = 'SHOW_REGION_USERS'
export const SEARCH_REGION_USERS = 'SEARCH_REGION_USERS'
export const REGION_SUGGESTIONS_USERS = 'REGION_SUGGESTIONS_USERS'
export const SELECTED_REGION_USERS = 'SELECTED_REGION_USERS'

export const SHOW_STATION_USERS = 'SHOW_STATION_USERS'
export const SEARCH_STATION_USERS = 'SEARCH_STATIONS_USERS'
export const STATION_SUGGESTIONS_USERS = 'STATION_SUGGESTIONS_USERS'
export const SELECTED_STATION_USERS = 'SELECTED_STATION_USERS'

export const SHOW_SECTOR_USERS = 'SHOW_SECTOR_USERS'
export const SEARCH_SECTOR_USERS = 'SEARCH_SECTOR_USERS'
export const SECTOR_SUGGESTIONS_USERS = 'SECTOR_SUGGESTIONS_USERS'
export const SELECTED_SECTOR_USERS = 'SELECTED_SECTOR_USERS'

export const MODAL_CALENDAR_USERS = 'MODAL_CALENDAR_USERS'
export const SET_CALENDAR_DATE_START_USERS = 'SET_CALENDAR_DATE_START_USERS'
export const SET_CALENDAR_DATE_END_USERS = 'SET_CALENDAR_DATE_END_USERS'
export const SET_SELECTED_TIME_LAPSE_USERS = 'SET_SELECTED_TIME_LAPSE_USERS'

export const REGION_INPUT_CHANGE_USERS = 'REGION_INPUT_CHANGE_USERS'
export const STATION_INPUT_CHANGE_USERS = 'STATION_INPUT_CHANGE_USERS'
export const SECTOR_INPUT_CHANGE_USERS = 'SECTOR_INPUT_CHANGE_USERS'

//API RESQUESTS
export const SERVICE_REQUESTING_USERS = 'SERVICE_REQUESTING_USERS'
export const SERVICE_SUCCESS_USERS = 'SERVICE_SUCCESS_USERS'

export const REGION_REQUESTING_USERS = 'REGION_REQUESTING_USERS'
export const REGION_SUCCESS_USERS = 'REGION_SUCCESS_USERS'

export const STATION_REQUESTING_USERS = 'STATION_REQUESTING_USERS'
export const STATION_SUCCESS_USERS = 'STATION_SUCCESS_USERS'

export const SECTOR_REQUESTING_USERS = 'SECTOR_REQUESTING_USERS'
export const SECTOR_SUCCESS_USERS = 'SECTOR_SUCCESS_USERS'

export const STATISTICS_REQUESTING_USERS = 'STATISTICS_REQUESTING_USERS'
export const STATISTICS_SUCCESS_USERS = 'STATISTICS_SUCCESS_USERS'

export const SET_CHART_OPTIONS_USERS = 'SET_CHART_OPTIONS_USERS'
export const SELECTED_GROUP_USERS = 'SELECTED_GROUP_USERS'
export const SET_STATE_GROUP_MENU_USERS = 'SET_STATE_GROUP_MENU_USERS'
