export const SET_THEME_DARK = 'SET_THEME_DARK'
export const SET_THEME_WHITE = 'SET_THEME_WHITE'
export const SET_THEME_BLUEDARK = 'SET_THEME_BLUEDARK'
export const SET_THEME_FROM_LOCALSTORAGE = 'SET_THEME_FROM_LOCALSTORAGE'
