// Charts Constants
export const SET_STATE_CHART_OPTIONS_STATES_ERLANG =
  'SET_STATE_CHART_OPTIONS_STATES_ERLANG'
export const SET_STATE_CHART_OPTIONS_STATES_PAYLOAD =
  'SET_STATE_CHART_OPTIONS_STATES_PAYLOAD'
export const SET_STATE_CHART_OPTIONS_STATES_CCR =
  'SET_STATE_CHART_OPTIONS_STATES_CCR'
export const SET_STATE_CHART_OPTIONS_STATES_PCR =
  'SET_STATE_CHART_OPTIONS_STATES_PCR'
export const SET_STATE_CHART_OPTIONS_STATES_USERS =
  'SET_STATE_CHART_OPTIONS_STATES_USERS'

export const SET_CONFIG_CLEAN_SERIES_STATES_ERLANG =
  'SET_CONFIG_CLEAN_SERIES_STATES_ERLANG'
export const SET_CONFIG_CLEAN_SERIES_STATES_PAYLOAD =
  'SET_CONFIG_CLEAN_SERIES_STATES_PAYLOAD'
export const SET_CONFIG_CLEAN_SERIES_STATES_CCR =
  'SET_CONFIG_CLEAN_SERIES_STATES_CCR'
export const SET_CONFIG_CLEAN_SERIES_STATES_PCR =
  'SET_CONFIG_CLEAN_SERIES_STATES_PCR'
export const SET_CONFIG_CLEAN_SERIES_STATES_USERS =
  'SET_CONFIG_CLEAN_SERIES_STATES_USERS'

export const SET_PRELOADER_STATE_STATES_ERLANG =
  'SET_PRELOADER_STATE_STATES_ERLANG'
export const SET_PRELOADER_STATE_STATES_PAYLOAD =
  'SET_PRELOADER_STATE_STATES_PAYLOAD'
export const SET_PRELOADER_STATE_STATES_CCR = 'SET_PRELOADER_STATE_STATES_CCR'
export const SET_PRELOADER_STATE_STATES_PCR = 'SET_PRELOADER_STATE_STATES_PCR'
export const SET_PRELOADER_STATE_STATES_USERS =
  'SET_PRELOADER_STATE_STATES_USERS'

//Breadcrumb constants
export const MENU_SELECTOR_LAPSE_STATES = 'MENU_SELECTOR_LAPSE_STATES'

export const SHOW_REGION_STATES = 'SHOW_REGION_STATES'
export const SEARCH_REGION_STATES = 'SEARCH_REGION_STATES'
export const REGION_SUGGESTIONS_STATES = 'REGION_SUGGESTIONS_STATES'
export const SELECTED_REGION_STATES = 'SELECTED_REGION_STATES'

export const SHOW_STATE = 'SHOW_STATE'
export const SEARCH_STATES = 'SEARCH_STATES'
export const STATES_SUGGESTIONS = 'STATES_SUGGESTIONS'
export const SELECTED_STATE = 'SELECTED_STATE'

export const MODAL_CALENDAR_STATES = 'MODAL_CALENDAR_STATES'
export const SET_CALENDAR_DATE_START_STATES = 'SET_CALENDAR_DATE_START_STATES'
export const SET_CALENDAR_DATE_END_STATES = 'SET_CALENDAR_DATE_END_STATES'
export const SET_SELECTED_TIME_LAPSE_STATES = 'SET_SELECTED_TIME_LAPSE_STATES'

export const REGION_INPUT_CHANGE_STATES = 'REGION_INPUT_CHANGE_STATES'
export const STATES_INPUT_CHANGE = 'STATES_INPUT_CHANGE'

//API RESQUESTS
export const REGION_REQUESTING_STATES = 'REGION_REQUESTING_STATES'
export const REGION_SUCCESS_STATES = 'REGION_SUCCESS_STATES'

export const STATES_REQUESTING = 'STATES_REQUESTING'
export const STATES_SUCCESS = 'STATES_SUCCESS'

export const STATISTICS_REQUESTING_STATES_ERLANG =
  'STATISTICS_REQUESTING_STATES_ERLANG'
export const STATISTICS_SUCCESS_STATES_ERLANG =
  'STATISTICS_SUCCESS_STATES_ERLANG'

export const STATISTICS_REQUESTING_STATES_PAYLOAD =
  'STATISTICS_REQUESTING_STATES_PAYLOAD'
export const STATISTICS_SUCCESS_STATES_PAYLOAD =
  'STATISTICS_SUCCESS_STATES_PAYLOAD'

export const STATISTICS_REQUESTING_STATES_CCR =
  'STATISTICS_REQUESTING_STATES_CCR'
export const STATISTICS_SUCCESS_STATES_CCR = 'STATISTICS_SUCCESS_STATES_CCR'

export const STATISTICS_REQUESTING_STATES_PCR =
  'STATISTICS_REQUESTING_STATES_PCR'
export const STATISTICS_SUCCESS_STATES_PCR = 'STATISTICS_SUCCESS_STATES_PCR'

export const STATISTICS_REQUESTING_STATES_USERS =
  'STATISTICS_REQUESTING_STATES_USERS'
export const STATISTICS_SUCCESS_STATES_USERS = 'STATISTICS_SUCCESS_STATES_USERS'

//Charts Options
export const SET_CHART_OPTIONS_STATES_ERLANG = 'SET_CHART_OPTIONS_STATES_ERLANG'
export const SET_CHART_OPTIONS_STATES_PAYLOAD =
  'SET_CHART_OPTIONS_STATES_PAYLOAD'
export const SET_CHART_OPTIONS_STATES_CCR = 'SET_CHART_OPTIONS_STATES_CCR'
export const SET_CHART_OPTIONS_STATES_PCR = 'SET_CHART_OPTIONS_STATES_PCR'
export const SET_CHART_OPTIONS_STATES_USERS = 'SET_CHART_OPTIONS_STATES_USERS'

export const SELECTED_GROUP_STATES = 'SELECTED_GROUP_STATES'

export const SET_STATE_GROUP_MENU_STATES = 'SET_STATE_GROUP_MENU_STATES'

export const CHANGE_CONSULT_STATE_STATES = 'CHANGE_CONSULT_STATE_STATES'

export const SET_CHART_OPTIONS_STATES_CONSULT =
  'SET_CHART_OPTIONS_STATES_CONSULT'

export const SET_STATE_CHART_OPTIONS_STATES_CONSULT =
  'SET_STATE_CHART_OPTIONS_STATES_CONSULT'

export const SET_PRELOADER_STATE_STATES_CONSULT =
  'SET_PRELOADER_STATE_STATES_CONSULT'

export const STATISTICS_SUCCESS_STATES_CONSULT =
  'STATISTICS_SUCCESS_STATES_CONSULT'

export const SELECTED_SERVICE_STATES_CONSULT = 'SELECTED_SERVICE_STATES_CONSULT'

export const STATISTICS_REQUESTING_STATES_CONSULT =
  'STATISTICS_REQUESTING_STATES_CONSULT'

export const SET_CONFIG_CLEAN_SERIES_STATES_CONSULT =
  'SET_CONFIG_CLEAN_SERIES_STATES_CONSULT'
